
server:
  port: 3000

spring:
  jwt:
    secrete:
      secreteKey: c3ByaW5nand07Iuc7YGs66a/7YKk7J6F64uI64ukISEhYmFzZTY066GcIOyCrOyghOyXkCDsnbjsvZTrlKntlojsirXri4jri6Qu
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3309/crud_db
      username: test
      password: 1234
      driverClassName: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:xml/**/*.xml
  configuration:
    map-underscore-to-camel-case:
      true