
server:
  port: 3000

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3309/crud_db
      username: test
      password: 1234
      driverClassName: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:xml/**/*.xml
  configuration:
    map-underscore-to-camel-case:
      true