
server:
  port = 3000

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url=jdbc:mariadb://localhost:3309/curd_db
      username=test
      password=mysql

mybatis:
  configuration:
    map-underscore-to-camel-case=true